---
output: 
  officedown::rdocx_document:
    base_format: "bookdown::word_document2"
    reference_docx: ASSETS/WORD-DOCUMENT/STYLE.docx
    tables:
      style: Normal Sin Sangria
      caption:
       style: Table Caption
       pre: 'TABLA '
       sep: " <w:br/>"
    plots:
      style: Normal Sin Sangria
      align: center
      topcaption: true
      caption:
       style: Image Caption
       pre: 'FIGURA '
       sep: " <w:br/>"
    number_sections: true
bibliography: [ASSETS/BIB/references.bib]
nocite: '@*'
csl: ASSETS/WORD-DOCUMENT/CLS/apa.csl
---

<!-- Configuración CHUNKS -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align='center',
                      fig.cap = TRUE,
                      dpi=700)

rootProyectMain <- 'LASPUMSS/COMPOSICION-DE-CARTERA-DEL-SISTEMA-FINANCIERO-DE-BOLIVIA/RECURSOS-INVESTIGACION/WORD-DOCUMENT/'
knitr::opts_knit$set(root.dir = getwd())
options(scipen=999)


require(officedown)
require(officer)

br <- officer::run_linebreak()

ps <- officer::prop_section(
    page_size = page_size(orient = "portrait"),
    type = "continuous"
)

ft <- fp_text(color = 'black', bold = TRUE, font.size = 10)
```


<!-- CARATULA -->
<!---BLOCK_POUR_DOCX{file: 'RECURSOS-INVESTIGACION/WORD-DOCUMENT/000-PREAMBULO/PRIMERA-PAGINA.docx'}--->

\newpage
<!-- INTRODUCCIÓN -->
```{r, child = paste0(rootProyectMain,"001-INTRODUCCION/001-INTRODUCCION.Rmd") }
```

<!-- MÉTODOS -->
```{r, child=paste0(rootProyectMain,"002-METODOS/002-METODOS.Rmd")}
```

\newpage
<!-- RESULTADOS -->
```{r, child=paste0(rootProyectMain,"003-RESULTADOS/003-RESULTADOS.Rmd")}
```


<!-- CONCLUSIÓN -->
```{r, child=paste0(rootProyectMain,"004-CONCLUSIONES/004-CONCLUSIONES.Rmd")}
```

\newpage
<!-- REFERENCIAS -->
```{r, child=paste0(rootProyectMain,"005-REFERENCIAS/005-REFERENCIAS.Rmd")}
```


